apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingestionSecrets.resourceName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.ingestionSecrets.awsAccessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.ingestionSecrets.awsSecretAccessKey | b64enc | quote }}
  HUGGINGFACE_API_TOKEN: {{ .Values.ingestionSecrets.huggingfaceAPIToken | b64enc | quote }}
