minio:
  resourceName: "minio-creds"
  awsAccessKeyId: "placeholder"
  awsSecretAccessKey: "placeholder"

modelIngestion:
  resourceName: "model-ingestion"
  image: "alpine:latest"

serviceAccount:
  resourceName: goku-sa

role:
  resourceName: goku-role

roleBinding:
  resourceName: goku-rolebinding