minio:
  resourceName: "minio-creds"
  awsAccessKeyId: "placeholder"
  awsSecretAccessKey: "placeholder"

modelIngestion:
  resourceName: "model-ingestion"
  image: "alpine:latest"

serviceAccount:
  name: goku-sa

role:
  name: goku-role

roleBinding:
  name: goku-rolebinding