minio:
  resourceName: "minio-creds"
  awsAccessKeyId: "placeholder"
  awsSecretAccessKey: "placeholder"

modelIngestion:
  resourceName: "model-ingestion"
  image: "aishwaryaprabhat/goku:goku:v0.1.0"
  MINIO_URI: "http://minio.minio.svc:9000"
  HF_MODEL_NAME: "mistralai/Mistral-7B-Instruct-v0.2"
  MLFLOW_TRACKING_URI: "http://mlflow.mlflow.svc:5000"
  MLFLOW_EXPERIMENT_NAME: hf-model-ingest

serviceAccount:
  resourceName: goku-sa

role:
  resourceName: goku-role

roleBinding:
  resourceName: goku-rolebinding