apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.modelIngestion.resourceName }}
  namespace: {{ .Release.Namespace }}
spec:
  entrypoint: dag
  arguments:
    parameters:
      - name: HF_MODEL_NAME
        value: "Mistral-7B-Instruct-v0.2"  # Default value can be set here if needed
  ttlStrategy:
    secondsAfterCompletion: 3600
  podGC:
    strategy: OnPodSuccess
    ttlSecondsAfterFinished: 360
    labelSelector:
      matchLabels:
        gcOnSuccess: "true"
  serviceAccountName: {{ .Values.serviceAccount.resourceName }}
  templates:
    - name: general-template
      inputs:
        parameters:
          - name: command
          - name: args
      metadata: 
        labels:
          gcOnSuccess: "true"
      container:
        image: {{ .Values.modelIngestion.image }}
        command: [{{ "{{inputs.parameters.command}}" | quote }}]
        args: [{{ "{{inputs.parameters.args}}" | quote }}]
        env:
          - name: HF_MODEL_NAME
            value: {{ "{{workflow.parameters.HF_MODEL_NAME}}" | quote }}
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.modelIngestion.MLFLOW_TRACKING_URI }}
          - name: MLFLOW_S3_ENDPOINT_URL
            value: {{ .Values.modelIngestion.MLFLOW_S3_ENDPOINT_URL }}
          - name: HUGGINGFACE_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ingestionSecrets.resourceName }}
                key: HUGGINGFACE_API_TOKEN
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ingestionSecrets.resourceName }}
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.ingestionSecrets.resourceName }}
                key: AWS_SECRET_ACCESS_KEY
    - name: dag
      dag:
        tasks:
          - name: ingest-model
            template: general-template
            arguments:
              parameters:
                - name: 'python'
                  value: "echo"
                - name: 'ingest_model.py'
                  value: "Ingesting model..."
