apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.modelIngestion.resourceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ttlStrategy:
    secondsAfterCompletion: 3600  # Set the TTL for workflow completion
  podGC:
    strategy: OnPodSuccess  # Define garbage collection strategy
    ttlSecondsAfterFinished: 3600 # Pods are cleaned up 1 hour after the workflow succeeds
    labelSelector:
      matchLabels:
        gcOnSucess: "true"
  entrypoint: dag
  serviceAccountName: "goku-sa"
  templates:
    - name: preflight-check
      metadata: 
        labels:
          gcOnSucess: "true"
      container:
        image: {{ .Values.modelIngestion.image }}
        command: [echo]
        args: ["preflight check"]
    - name: ingest-model
      metadata: 
        labels:
          gcOnSucess: "true"
      container:
        image: {{ .Values.modelIngestion.image }}
        command: [echo]
        args: ["postflight check"]
    - name: postflight-check
      metadata: 
        labels:
          gcOnSucess: "true"
      container:
        image: {{ .Values.modelIngestion.image }}
        command: [echo]
        args: ["postflight check"]
    - name: dag
      dag:
        tasks:
          - name: preflight-check
            template: preflight-check
          - name: ingest-model
            template: ingest-model
            dependencies: ['preflight-check']
          - name: postflight-check
            template: postflight-check
            dependencies: ['ingest-model']
