apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Values.modelIngestion.resourceName }}
  namespace: {{ .Release.Namespace }}
spec:
  entrypoint: dag
  arguments:
    parameters:
      - name: HF_MODEL_NAME
        value: "Mistral-7B-Instruct-v0.2"  # Default value can be set here if needed
  ttlStrategy:
    secondsAfterCompletion: 3600
  podGC:
    strategy: OnPodSuccess
    ttlSecondsAfterFinished: 360
    labelSelector:
      matchLabels:
        gcOnSuccess: "true"
  serviceAccountName: {{ .Values.serviceAccount.resourceName }}
  templates:
    - name: general-template
      inputs:
        parameters:
          - name: command
          - name: args
      metadata: 
        labels:
          gcOnSuccess: "true"
      container:
        image: {{ .Values.modelIngestion.image }}
        command: [{{ "{{inputs.parameters.command}}" | quote }}]
        args: [{{ "{{inputs.parameters.args}}" | quote }}]
        env:
          - name: HF_MODEL_NAME
            value: "{{workflow.parameters.HF_MODEL_NAME}}"
          - name: MLFLOW_TRACKING_URI
            value: {{ .Values.modelIngestion.MLFLOW_TRACKING_URI }}
          - name: MLFLOW_EXPERIMENT_NAME
            value: {{ .Values.modelIngestion.MLFLOW_EXPERIMENT_NAME }}
          - name: MINIO_URI
            value: {{ .Values.modelIngestion.MINIO_URI }}
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.minio.resourceName }}
                key: awsAccessKeyId
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.minio.resourceName }}
                key: awsSecretAccessKey
    - name: dag
      dag:
        tasks:
          - name: preflight-check-mlflow
            template: general-template
            arguments:
              parameters:
                - name: command
                  value: "python"
                - name: args
                  value: "-c verify_mlflow.py"
          - name: ingest-model
            dependencies: ["preflight-check-minio", "preflight-check-mlflow"]
            template: general-template
            arguments:
              parameters:
                - name: command
                  value: "echo"
                - name: args
                  value: "Ingesting model..."
