apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: raycluster
  namespace: argocd
spec:
  destination:
    namespace: raycluster
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: ray-cluster
    helm:
      parameters:
      - name: image.tag
        value: "2.7.0"
      - name: head.containerEnv[0].name
        value: RAY_GRAFANA_IFRAME_HOST
      - name: head.containerEnv[0].value
        value: http://127.0.0.1:3000
      - name: head.containerEnv[1].name
        value: RAY_GRAFANA_HOST
      - name: head.containerEnv[1].value
        value: http://prometheus-grafana.prometheus-system.svc:80
      - name: head.containerEnv[2].name
        value: RAY_PROMETHEUS_HOST
      - name: head.containerEnv[2].value
        value: http://prometheus-kube-prometheus-prometheus.prometheus-system.svc:9090
      - name: cluster.workerGroups.smallGroup.resources.limits.cpu
        value: "1"
      - name: cluster.workerGroups.smallGroup.resources.limits.memory
        value: 1G
      - name: cluster.workerGroups.smallGroup.resources.requests.cpu
        value: "1"
      - name: cluster.workerGroups.smallGroup.resources.requests.memory
        value: 1G
      - name: cluster.head.resources.limits.cpu
        value: "1"
      - name: cluster.head.resources.limits.memory
        value: 2G
      - name: cluster.head.resources.requests.cpu
        value: "1"
      - name: cluster.head.resources.requests.memory
        value: 2G
      valueFiles:
      - values.yaml
    repoURL: https://ray-project.github.io/kuberay-helm/
    targetRevision: 1.1.0
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
