# Complete workflowtemplate.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: model-ingestion
  namespace: "{{ .Values.model-ingestion.namespace }}"
spec:
  entrypoint: ingest-model
  arguments:
    parameters:
    - name: huggingface-repo
      value: "{{ .Values.model-ingestion.huggingfaceRepo }}"
    - name: model-name
      value: "{{ .Values.model-ingestion.modelName }}"
    - name: mlflow-experiment-name
      value: "{{ .Values.model-ingestion.mlflowExperimentName }}"
  ttlStrategy:
    secondsAfterCompletion: 3600 # TTL 1 hour
  podGC:
    strategy: OnPodCompletion
    deleteDelay: 300 # GC successful pods after 30s
  templates:
    - name: ingest-model
      # Define your task templates (e.g., verify-model, download-and-log, verify-log)
      # Make sure to adjust the container env to reference the Kubernetes Secret
      container:
        image: "{{ .Values.model-ingestion.image }}"
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: minio-aws-credentials
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: minio-aws-credentials
                key: aws-secret-access-key
          - name: MLFLOW_TRACKING_URI
            value: "{{ .Values.model-ingestion.mlflowTrackingUri}}"
          - name: MLFLOW_EXPERIMENT_NAME
            value: "{{ .Values.model-ingestion.mlflowExperimentName}}"
          - name: HUGGINGFACE_REPO
            value: "{{ .Values.model-ingestion.huggingfaceRepo}}"
          - name: MODEL_NAME
            value: "{{ .Values.model-ingestion.modelName}}"
        command: [sh, -c]
        args: ["python download_model.py && python log_model.py"]
      # Add other tasks and their templates as needed
