apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goku
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aishwaryaprabhat/GOKU'
    path: goku/chart
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: ingestionSecrets.awsAccessKeyId
          value: plaholder
        - name: ingestionSecrets.awsSecretAccessKey
          value: placeholder
        - name: ingestionSecrets.huggingfaceAPIToken
          value: placeholder
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: goku
  syncPolicy:
    syncOptions:
      - CreateNamespace=true